version: '3'
services:
    client:
      image: theanuragshukla/omegle-client
      ports:
        - 3001:80
      env:
        - REACT_APP_PEER_HOST: server
        - REACT_APP_PEER_PORT: 8000
        - REACT_APP_SERVER_URL: server

    server:
      ports:
        - 5000:8000
      env:
        - CLIENT_URL: client
        - MONGO_URL: $MONGO_URL
      env_file: .env
