version: '3'
services:
    client:
      image: theanuragshukla/omegle
      ports:
        - 3002:80

    server:
      container_name: 'omeserver'
      build:
        args:
          MONGO_URL: ${MONGO_URL}
          CLIENT_URL: https://omegle.anurags.tech
        dockerfile: Dockerfile
        context: ./server/
      ports:
        - 8002:8000
      env_file: .env
